import type { FlowGraph, FlowNode, FlowEdge } from '@/types';

/** Generate Python code from a FlowGraph via topological traversal. */
export function generatePythonCode(graph: FlowGraph): string {
  const sorted = topoSort(graph.nodes, graph.edges);
  const lines: string[] = [
    '# Auto-generated by Yyds Flow Editor',
    'from yyds import *',
    '',
    '',
    'def main():',
  ];

  const indentStack: number[] = [1]; // base indent inside main()
  const indent = () => '    '.repeat(indentStack[indentStack.length - 1]);

  for (const node of sorted) {
    const d = node.data as Record<string, unknown>;
    switch (node.type) {
      case 'start':
        lines.push(`${indent()}# ── Start ──`);
        break;
      case 'end':
        lines.push(`${indent()}# ── End ──`);
        break;
      case 'click':
        lines.push(`${indent()}yyds.click(${d.x}, ${d.y}, ${d.clickTime ?? 1}, ${d.interval ?? 50})`);
        break;
      case 'swipe':
        lines.push(`${indent()}yyds.swipe(${d.x1}, ${d.y1}, ${d.x2}, ${d.y2}, ${d.duration ?? 300})`);
        break;
      case 'input_text':
        lines.push(`${indent()}yyds.set_text(${pyStr(d.text)})`);
        break;
      case 'ocr_find':
        lines.push(`${indent()}result = yyds.ocr(${pyStr(d.text)}, timeout=${d.timeout ?? 10})`);
        break;
      case 'ocr_click':
        lines.push(`${indent()}yyds.ocr_click_if_found(${pyStr(d.text)}, timeout=${d.timeout ?? 10})`);
        break;
      case 'find_image':
        lines.push(`${indent()}result = yyds.find_image(${pyStr(d.template)}, threshold=${d.threshold ?? 0.8})`);
        break;
      case 'condition':
        lines.push(`${indent()}if ${d.expression || 'True'}:`);
        indentStack.push(indentStack[indentStack.length - 1] + 1);
        break;
      case 'loop':
        if (d.mode === 'count') {
          lines.push(`${indent()}for i in range(${d.count ?? 10}):`);
        } else {
          lines.push(`${indent()}while ${d.expression || 'True'}:`);
        }
        indentStack.push(indentStack[indentStack.length - 1] + 1);
        break;
      case 'wait':
        lines.push(`${indent()}yyds.wait_until(${pyStr(d.condition)}, timeout=${d.timeout ?? 10})`);
        break;
      case 'sleep':
        lines.push(`${indent()}yyds.sleep(${d.seconds ?? 1})`);
        break;
      case 'shell':
        lines.push(`${indent()}yyds.shell(${pyStr(d.command)})`);
        break;
      case 'open_app':
        lines.push(`${indent()}yyds.open_app(${pyStr(d.package)})`);
        break;
      case 'screenshot':
        lines.push(`${indent()}yyds.screenshot(${pyStr(d.savePath)})`);
        break;
      case 'log':
        lines.push(`${indent()}print(${pyStr(d.message)})`);
        break;
      case 'sub_flow':
        lines.push(`${indent()}# TODO: sub_flow ${pyStr(d.flowFile)}`);
        break;
    }
  }

  // Close any remaining indent blocks with pass if needed
  while (indentStack.length > 1) {
    indentStack.pop();
    lines.push(`${'    '.repeat(indentStack[indentStack.length - 1])}pass`);
  }

  lines.push('', '', 'if __name__ == "__main__":', '    main()', '');
  return lines.join('\n');
}

// ── Helpers ──

function pyStr(val: unknown): string {
  const s = String(val ?? '');
  // Escape backslashes and quotes for Python string literal
  const escaped = s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  return `'${escaped}'`;
}

/** Kahn's algorithm topological sort following edges source→target. */
function topoSort(nodes: FlowNode[], edges: FlowEdge[]): FlowNode[] {
  const nodeMap = new Map(nodes.map(n => [n.id, n]));
  const inDegree = new Map<string, number>();
  const adj = new Map<string, string[]>();

  for (const n of nodes) {
    inDegree.set(n.id, 0);
    adj.set(n.id, []);
  }
  for (const e of edges) {
    adj.get(e.source)?.push(e.target);
    inDegree.set(e.target, (inDegree.get(e.target) ?? 0) + 1);
  }

  const queue: string[] = [];
  for (const [id, deg] of inDegree) {
    if (deg === 0) queue.push(id);
  }

  const result: FlowNode[] = [];
  while (queue.length > 0) {
    const id = queue.shift()!;
    const node = nodeMap.get(id);
    if (node) result.push(node);
    for (const next of adj.get(id) ?? []) {
      const d = (inDegree.get(next) ?? 1) - 1;
      inDegree.set(next, d);
      if (d === 0) queue.push(next);
    }
  }

  // Append any unreachable nodes at the end
  for (const n of nodes) {
    if (!result.includes(n)) result.push(n);
  }

  return result;
}
